### ISSUE TITLE
Cpp/c language support

### ISSUE THREAD

**Issue by Dark-Passenger** [bryphe/oni#253]
Love the work but I work on cpp and c code bases sometimes even Python... Where is the love for us...

**Comment by extr0py** [comment]
Once #6 is implemented, we'll be able to pick up implementations for C++, C, and python. So it's definitely in the works :)

**Comment by TalAmuyal** [comment]
In the meantime, you can install a plugin for neovim and have it in Oni
that way.
I have youcompleteme, and it works pretty good.

**Comment by Dark-Passenger** [comment]
@TalAmuyal awesome. But does it seem native ? like look and feel ? thats why we use this right :D

**Comment by bert88sta** [comment]
Sorry guys, it was pretty late when I wrote this. I'll fix soon

On Feb 26, 2017 3:03 AM, "Dhruv Paranjape" <notifications@github.com> wrote:

@TalAmuyal <https://github.com/TalAmuyal> awesome. But does it seem native
? like look and feel ? thats why we use this right :D

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/extr0py/oni/issues/253#issuecomment-282540027>, or mute
the thread

**Comment by bert88sta** [comment]
YCM is not cross-platform friendly, which means a good bit of software bundling. I don't know if extr0py is up for it or not. However, you could still use it for yourself. You're not limited to the default init.vim in Oni, so you can port over your prior YCM setup and whatnot

**Comment by extr0py** [comment]
The nice thing is that, since Neovim enables the `externalpopupmenu` UI option, and we pick that up in Oni  is that regardless of your completion provider (vanilla omnicomplete, YCM, deoplete, etc) - you should get that same look and feel. There are some bugs around this but that is the goal.

On top of that, Oni will expose some additional rich completion options (like completion signature details, method signature help) that there isn't really a concept for in vanilla Vim or Neovim today. The language server protocol gives us this information, and so Oni can act as a bridge this into the Vim world.

For YCM, I had a heck of a time getting it running on Windows. It was pretty brutal... Lots of issues with Python versions, conflicts with some ms*.dlls, etc... For Oni, I want that to be a bit easier :)

**Comment by TalAmuyal** [comment]
For me, I just couldn't get YCM to work with Vim.
In contrast, with Neovim it worked on the first try.

As for the language-server -protocol, recently, LLVM/Clang started a new
sub-project, `clangd`, which seems to match Oni perfectly for C/C++ users.
YCM is a plugin built on Clang, but clangd is *meant* to be used exactly
for that purpose and with a wider audience, as it will not target a
specific IDE or editor.

Dhruv Paranjape, I've yet to have a full work day of using Oni but so far
YCM + Oni seems as great as in Neovim.
I'm trying to configure Oni so it will be a match for my current Neovim
configuration.

When I'm there (and probably along the way). I'll update ;)

**Comment by keforbes** [comment]
Changing difficulty to medium now that #6 is implemented.

I think this will still be on hold until Clang 5.0 comes out.  It looks like Clang 5.0 will come with `clangd`, which implements the language server protocol.
https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Clang-Clangd-Server

**Comment by TalAmuyal** [comment]
Hi, long time no see!

**clang 5** has been officially released, and **clangd** is available.

Since I want it supported by Oni, I've taken the initiative and started implementing its' support (using oni-plugin-python as an example).

Questions:

1. Is anybody currently working on this? (if so, let's join forces!)
2. Are there any tips for implementing a new LSP client?

**Comment by extr0py** [comment]
Hey @TalAmuyal ! This is awesome! Thanks for looking into this, would be really cool to have this support.

I haven't heard of anyone investigating this today - I'm working a bit on #504 (which is another language client for Java).

The approach that `oni-plugin-python` takes sounds like the best approach for now, and `oni-plugin-golang` is another sample.

Some of the language clients need more, like finding a root project (for example, the C# plugin needs to find the root `.csproj` file - https://github.com/extr0py/oni-language-csharp/blob/e59ebe2b53b96e10b177a9c31a3700ba3601acfe/lib/index.js#L15). I looked over the vscode plugin for clangd and doesn't seem like this would be necessary.

As far as tips go, here's what I can think of off the top of my head...
- Using the python one is a great starting point - you'll need to change the `supportedFileTypes` in the package.json. 
- You can remove the `disableDocumentSymbol` option 
- I'd recommend with building with `npm run build-debug` and using the developer console (open the dev tools via `Control+Shift+P` - errors with the language server integration tend to show up here).

Let me know if you hit any issues or have any questions.

**Comment by TalAmuyal** [comment]
@bryphe, it's not perfect but I believe that #757 addressed this issue.
Should it be closed now?

**Comment by bryphe** [comment]
@TalAmuyal - Ah yes, definitely - agree #757 addresses this, and we can track any issues in separate work items. 

Thanks for your investigation and work on this! 👍
