### ISSUE TITLE
Can not switch non-English input method, such as Chinese input software

### ISSUE THREAD

**Issue by saibing** [bryphe/oni#396]
Oni is very outstanding, Thank you for great work.

I use Oni on windows 7, programming and write markdown.

I found it can not switch non-English input method, such as Chinese input software.

I'm coming from China, so I need input some Chinese on write markdown.

Can you help me?

**Comment by keforbes** [comment]
@saibing, can you give a little more detail?  I don't know what it means to change the input method in vim.  Is there a command you're trying to run which fails in Oni?

**Comment by extr0py** [comment]
Windows has a concept of an [IME](https://msdn.microsoft.com/en-us/library/windows/desktop/ee418266(v=vs.85).aspx), which lets you use extended character sets of change the keyboard layout. In theory this should work by default in the browser with input forms, but I'm guessing because we just pick up key events, IME doesn't work correctly.

@saibing - would it be possible to get a video or screenshot of the IME you use that works outside of Oni? Thanks!

**Comment by saibing** [comment]
@keforbes @extr0py 
I feel very sorry when I want to upload pictures to github, github reported the following error:

```error
Something went really wrong, and we can't process that file. Try again
```

I think you are right, The issue should be caused by the IME event process.

**Comment by destinyd** [comment]
i need it

**Comment by destinyd** [comment]
I need it too.
Working on macos.

**Comment by saibing** [comment]
Thanks :+1: 
Can you release a new version?

**Comment by bryphe** [comment]
Will do! I'll put up an RC build today.

Thanks for helping me validate, since I don't use the IME day-to-day there could still be bugs or corner cases. Let me know if there is anything still not working.

**Comment by saibing** [comment]
@bryphe 
Thank you very much. The chinese IME can work now.  I will use Oni as my daily-editor now. :+1:

**Comment by bryphe** [comment]
@saibing - that's great to hear! thank you for testing it out!  keep me posted on how it goes 😄
