### ISSUE TITLE
Display issue with status bar when changing font-size

### ISSUE THREAD

**Issue by badosu** [bryphe/oni#541]
Changing the font size on `config.js` refreshes the screen with a visual glitch in the status bar:

![2017-07-16-224658_1356x85_scrot](https://user-images.githubusercontent.com/347552/28253329-ed79b65c-6a78-11e7-8ea2-f0268bab2458.png)

It does not persist after closing and reopening the application.

**Comment by extr0py** [comment]
Thanks for reporting this, @badosu (and the screenshot!)

I'm able to reproduce. I believe it's due to our DOM renderer strategy not properly cleaning up after the resize. I'm actually in that space now looking at rendering and performance optimizations, so I'll see if I can tackle this as part of those changes.
