### ISSUE TITLE
Provide an option to configure the command palette appearance

### ISSUE THREAD

**Issue by badosu** [bryphe/oni#714]
This is how it's displayed on a high DPI high, font size screen:

![screenshot from 2017-09-18 17-32-07](https://user-images.githubusercontent.com/347552/30563185-74a55aaa-9c97-11e7-9e85-3b1998335b02.png)

**Comment by jordwalke** [comment]
Maybe we could start also by making its hue match the OneDark color theme (right now the command pallet has a warm hue and the OneDark base color is cooler (more blue)).

**Comment by extr0py** [comment]
Thanks for logging the issue @badosu ! This is very ugly. I believe it is the same issue in #713 (using pixels for font sizing), and would have a similiar fix.

The hue / colors are a good point too - I experimented a bit with using colors based on the current background / foreground colors of the vim colorscheme.

**Comment by bryphe** [comment]
This should be addressed with PR #749. I couldn't repo the High-DPI issue though unfortunately, but I believe it's due to a mismatch with font-size pixel vs point. The change uses `em` sizing for Oni's UI, so that it is a derivative of the font size specified in the settings. There were lots of places in CSS we used pixels, which would be problematic.. Feel free to reopen if you're still seeing this.

**Comment by badosu** [comment]
I wil create an `oni-git` package to try and reproduce from master branch.

**Comment by badosu** [comment]
👍  Works great, thanks!
