### ISSUE TITLE
Oni does not respect arguments on linux

### ISSUE THREAD

**Issue by badosu** [bryphe/oni#725]
Currently oni does not open a file when called with the file path as an argument on linux.

I'll try to take a look into this.

@bryphe Can you provide the specification on how the arguments should be parsed?

**Comment by bryphe** [comment]
Thanks for opening this issue, @badosu ! Made me realize I missed the thread in #645 

The screenshot you posted helps:
![screenshot from 2017-09-25 20-52-11](https://user-images.githubusercontent.com/347552/30836283-8da0464a-a233-11e7-9fa6-329a2c1d5f86.png)

In _development_ builds, for this scenario, you usually see __three__ arguments - the electron prebuilt binary, main.js, and the file.

However, for _packaged_ builds, the main.js is baked in the executable file, so you only see __two__ arguments as in your screenshot.

Accounting for this is handled here: https://github.com/bryphe/oni/blob/735985dd8e934ad4de389af82a2047dc269ef7bc/main/src/main.ts#L159

But today only OSX and Windows are handled. I think we need to add an additional case for linux, something like:

```
    const linuxOpenWith = platform === "linux" && args[0].indexOf("opt/oni") >= 0

    if (windowsOpenWith || macOpenWith || linuxOpenWith) {
        createWindow(args.slice(1), workingDirectory)
    } else {
        createWindow(args.slice(2), workingDirectory)
    }
```

**Comment by badosu** [comment]
Is there a reason for checking the executable path?

This will be troublesome for linking oni or installing it on non-opt directories (which should be the case).

I am fixing this at the moment and can't output any logs for debugging since it's a step before spawning the process, I tried `Log.info` but no dice, any idea?

**Comment by bryphe** [comment]
> This will be troublesome for linking oni or installing it in non-opt directories (which should be the case). I think it would be better to check if we are on a development build or not before compiling oni and setting a variable that can be captured there, what do you think?

Yes, this is a good point. I was thinking about this and it might be worth _inverting_ the condition - we could check if this is using the prebuilt electron, by checking for the presence of `node_modules/electron` in the first argument. If `node_modules/electron` is present in the path, we should use the 3 arg strategy, otherwise use the 2 args strategy. 

This has the advantage that it works the same across all platforms, and would be more resilient in the case of alternative paths. The only downside is if someone happened to install Oni in a path containing `node_modules/electron`, it would break, but I imagine that is unlikely..

An alternative strategy would be to set an environment variable when the development build of Oni is launched (by modifying the script in `cli/oni`). This would be deterministic, since it is used by `npm link` in all platforms, but is not used in the packaged builds.

> I am fixing this at the moment and can't output any logs for debugging since it's a step before spawning the process, I tried Log.info but no dice, any idea?

Ah yes, there's an undocumented way to get the logs from the main process from the debug window in the renderer process. You can run this command: `require("electron").remote.getGlobal("getLogs")()`.

Here's what it looks like on my machine:
![image](https://user-images.githubusercontent.com/13532591/30942462-3a2b8dbc-a3a0-11e7-8c93-4ac5309620f9.png)

**Comment by badosu** [comment]
Mine has `dist/electron` instead of `node_modules/electron` since I am testing the distribution build.

Would checking if it's terminated in `electron` be a bad idea?

**Comment by badosu** [comment]
I very much prefer the deterministic approach but I'm not sure of all the edge cases and how to send this state down the stack.

**Comment by bryphe** [comment]
> Would checking if it's terminated in electron be a bad idea?

Actually that seems reasonable. The only corner-case here is that you'd need to check for `electron.exe` on Windows, but that is still straightforward and deterministic. I like this approach!

If we decided to use an environment variable to gate this, we could do something like:

```
processOptions.env = Object.assign({}, process.env, {
    "LOCAL_ONI": 1,
})
```
(This preserves all the existing environment variables, and tacks on the `LOCAL_ONI` one... not sure if that is the best name for it...)

To: 
https://github.com/bryphe/oni/blob/fe7f2d89a69662574316ef4f1c35f9261422a6ae/cli/oni#L10

Then, in `main.ts`, we'd update the logic to gate on that environment variable, instead of trying to infer from the path:
```
    const isLocalBuild = process.env["LOCAL_ONI"]
    if (!isLocalBuild) {
        createWindow(args.slice(1), workingDirectory)
    } else {
        createWindow(args.slice(2), workingDirectory)
    }
```

But checking if the first argument is terminated in `electron` (or `electron.exe` for Windows), per your suggestion, seems simpler to me!

**Comment by badosu** [comment]
@bryphe See the PR referenced, I preferred to use the environment variable to make Oni more platform agnostic and also it's way simpler. I used the `LOCAL_ONI` name as it make the purpose self-explanatory.

**Comment by badosu** [comment]
As soon as you release a new version this will fix the expected behaviour on linux, so keep that in mind for the release notes.
