### ISSUE TITLE
Adjust tab header scaling issues

### ISSUE THREAD

**Issue by badosu** [bryphe/oni#783]
In line with the work being done to scale Oni's layout there's an issue that has been bothering me for some time.

If you use a bigger font size the tab header will not scale well, see:

![screenshot from 2017-10-11 12-27-59](https://user-images.githubusercontent.com/347552/31450472-e3132810-ae7f-11e7-8075-bf3238ff196f.png)

One possible solution is to use scalable units for the height and max-width of the tab element, I can take a stab at this if necessary.

**Comment by bryphe** [comment]
Ah yes, thanks for logging this! It's a similiar issue to what we saw with the status bar - there are a few hardcoded `px` values `Tabs.less`:

https://github.com/bryphe/oni/blob/1ad48df21ea1b62fcb51cd15df8c9a34420fdb4b/browser/src/UI/components/Tabs.less#L44

I think if we change the `max-height`, `min-height`, and `height` values to use `em` instead of `px`, that should solve the problem. 

If you want to give it a go @badosu , that would be great! I'll assign it to you for now - but LMK if you have any questions

**Comment by bryphe** [comment]
I merged in #832 - with the following configuration settings:
- `tabs.height` - set the size of individual tabs
- `tabs.maxWidth` - set the maximum width a tab can expand to
- `tabs.wrap` - set to `true` if you want the tabs to wrap, otherwise there will be a horizontal scrollbar for overflow.

I'll close for now, but keep me posted if they aren't behaving as expected. Thanks for the PR and brainstorming around this, @badosu !
